#*****************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# DataProcBoard_proj.tcl: Tcl script for re-creating project 'DataProcBoard'
#
# Generated by Vivado on Wed Jul 16 13:23:56 +0800 2025
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (DataProcBoard_proj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/project/DataProcBoard_new/src/rtl/TMP75.v"
#    "D:/project/DataProcBoard_new/src/rtl/CMAC/cmac_usplus_config.v"
#    "D:/project/DataProcBoard_new/src/rtl/CMAC/cmac_usplus_rx_config.v"
#    "D:/project/DataProcBoard_new/src/rtl/CMAC/cmac_usplus_tx_config.v"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_8b.v"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_zero_extnd.v"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/ernic_0_rnic_exdes_crc_wrap.v"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/ernic_0_rnic_exdes_icrc_calc.v"
#    "D:/project/DataProcBoard_new/src/rtl/CMAC/CMAC_monitor.sv"
#    "D:/project/DataProcBoard_new/src/rtl/DDR_PROC/DDR4_proc.sv"
#    "D:/project/DataProcBoard_new/src/rtl/define/XRNIC_define.vh"
#    "D:/project/DataProcBoard_new/src/rtl/define/Board_define.vh"
#    "D:/project/DataProcBoard_new/src/rtl/define/ETH_pkt_define.sv"
#    "D:/project/DataProcBoard_new/src/rtl/define/XRNIC_REG_configuration.vh"
#    "D:/project/DataProcBoard_new/src/rtl/DDR_PROC/DDR4_write_proc.sv"
#    "D:/project/DataProcBoard_new/src/rtl/define/proj_define.vh"
#    "D:/project/DataProcBoard_new/src/rtl/Data_proc_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/FAN_ctr_module.sv"
#    "D:/project/DataProcBoard_new/src/rtl/INFO_PROC/INFO_data_sim.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/QPn_LUT.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/RDMA_fsm.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA_proc_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/RoCE_CM_rx_proc.sv"
#    "D:/project/DataProcBoard_new/src/rtl/TDI_PROC/TDI_data_proc.sv"
#    "D:/project/DataProcBoard_new/src/rtl/TDI_PROC/TDI_data_proc_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/TDI_PROC/TDI_data_sim.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/XRNIC_WQE_manager_new.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/XRNIC_reg_config_fsm.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/XRNIC_rx_path_proc.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/XRNIC_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/arp_rx.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/arp_table.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/arp_tx.sv"
#    "D:/project/DataProcBoard_new/src/rtl/axi_bram.sv"
#    "D:/project/DataProcBoard_new/src/rtl/RDMA/axi_lite_interface.sv"
#    "D:/project/DataProcBoard_new/src/rtl/CMAC/cmac_usplus_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/eth_pkt_proc_top.sv"
#    "D:/project/DataProcBoard_new/src/rtl/rst_gen.sv"
#    "D:/project/DataProcBoard_new/src/rtl/rst_usr_gen.sv"
#    "D:/project/DataProcBoard_new/src/rtl/ETH_PKT_PROC/rx_pkt_decode.sv"
#    "D:/project/DataProcBoard_new/src/rtl/top.sv"
#    "D:/project/DataProcBoard_new/src/ip/vio_cmac/vio_cmac.xci"
#    "D:/project/DataProcBoard_new/src/ip/ila_cmac/ila_cmac.xci"
#    "D:/project/DataProcBoard_new/src/rtl/define/TDI_define.vh"
#    "D:/project/DataProcBoard_new/src/ip/ernic_0/ernic_0.xci"
#    "D:/project/DataProcBoard_new/src/ip/vio_reg_config/vio_reg_config.xci"
#    "D:/project/DataProcBoard_new/src/ip/ddr4_test/ddr4_test.xci"
#    "D:/project/DataProcBoard_new/src/ip/TDI_fifo/TDI_fifo.xci"
#    "D:/project/DataProcBoard_new/src/ip/clk_wiz_0/clk_wiz_0.xci"
#    "D:/project/DataProcBoard_new/src/ip/qp_blk_mem/qp_blk_mem.xci"
#    "D:/project/DataProcBoard_new/src/ip/qp_axi_bram_ctrl/qp_axi_bram_ctrl.xci"
#    "D:/project/DataProcBoard_new/src/ip/vio_rst/vio_rst.xci"
#    "D:/project/DataProcBoard_new/src/ip/vio_TDI_sim_param/vio_TDI_sim_param.xci"
#    "D:/project/DataProcBoard_new/src/ip/cmac_usplus/cmac_usplus.xci"
#    "D:/project/DataProcBoard_new/src/ip/axi_interconnect_0/axi_interconnect_0.xci"
#    "D:/project/DataProcBoard_new/src/xdc/config.xdc"
#    "D:/project/DataProcBoard_new/src/xdc/debug.xdc"
#    "D:/project/DataProcBoard_new/src/xdc/pin.xdc"
#    "D:/project/DataProcBoard_new/src/xdc/timing.xdc"
#    "D:/project/DataProcBoard_new/src/xdc/ddr4_c1_pin.xdc"
#    "D:/project/DataProcBoard_new/src/xdc/ddr4_c0_pin.xdc"
#    "D:/project/DataProcBoard_new/src/tb/Host_pkt_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/Host_sim.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/arch_defines.v"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/arch_package.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/MemoryArray.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_sdram_model_wrapper.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/proj_package.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/StateTableCore.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/StateTable.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_model.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_model_tb_top.sv"
#    "D:/project/DataProcBoard_new/src/tb/decompression.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/interface.sv"
#    "D:/project/DataProcBoard_new/src/tb/top_tb.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/bd_8530_lmb_bram_I_0.mem"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/bd_8530_second_lmb_bram_I_0.mem"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_axi_wrapper.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_custom_mode_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_prbs_mode_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/microblaze_mcs_0.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_boot_mode_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_axi_opcode_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_data_gen.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_axi_tg_top.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/ddr4_v2_2_data_chk.sv"
#    "D:/project/DataProcBoard_new/src/tb/ddr_sim/glbl.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/src/rtl/TMP75.v"]"\
 "[file normalize "$origin_dir/src/rtl/CMAC/cmac_usplus_config.v"]"\
 "[file normalize "$origin_dir/src/rtl/CMAC/cmac_usplus_rx_config.v"]"\
 "[file normalize "$origin_dir/src/rtl/CMAC/cmac_usplus_tx_config.v"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_8b.v"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_zero_extnd.v"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/ernic_0_rnic_exdes_crc_wrap.v"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/ernic_0_rnic_exdes_icrc_calc.v"]"\
 "[file normalize "$origin_dir/src/rtl/CMAC/CMAC_monitor.sv"]"\
 "[file normalize "$origin_dir/src/rtl/DDR_PROC/DDR4_proc.sv"]"\
 "[file normalize "$origin_dir/src/rtl/define/XRNIC_define.vh"]"\
 "[file normalize "$origin_dir/src/rtl/define/Board_define.vh"]"\
 "[file normalize "$origin_dir/src/rtl/define/ETH_pkt_define.sv"]"\
 "[file normalize "$origin_dir/src/rtl/define/XRNIC_REG_configuration.vh"]"\
 "[file normalize "$origin_dir/src/rtl/DDR_PROC/DDR4_write_proc.sv"]"\
 "[file normalize "$origin_dir/src/rtl/define/proj_define.vh"]"\
 "[file normalize "$origin_dir/src/rtl/Data_proc_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/FAN_ctr_module.sv"]"\
 "[file normalize "$origin_dir/src/rtl/INFO_PROC/INFO_data_sim.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/QPn_LUT.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/RDMA_fsm.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA_proc_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/RoCE_CM_rx_proc.sv"]"\
 "[file normalize "$origin_dir/src/rtl/TDI_PROC/TDI_data_proc.sv"]"\
 "[file normalize "$origin_dir/src/rtl/TDI_PROC/TDI_data_proc_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/TDI_PROC/TDI_data_sim.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/XRNIC_WQE_manager_new.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/XRNIC_reg_config_fsm.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/XRNIC_rx_path_proc.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/XRNIC_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/arp_rx.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/arp_table.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/arp_tx.sv"]"\
 "[file normalize "$origin_dir/src/rtl/axi_bram.sv"]"\
 "[file normalize "$origin_dir/src/rtl/RDMA/axi_lite_interface.sv"]"\
 "[file normalize "$origin_dir/src/rtl/CMAC/cmac_usplus_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/eth_pkt_proc_top.sv"]"\
 "[file normalize "$origin_dir/src/rtl/rst_gen.sv"]"\
 "[file normalize "$origin_dir/src/rtl/rst_usr_gen.sv"]"\
 "[file normalize "$origin_dir/src/rtl/ETH_PKT_PROC/rx_pkt_decode.sv"]"\
 "[file normalize "$origin_dir/src/rtl/top.sv"]"\
 "[file normalize "$origin_dir/src/ip/vio_cmac/vio_cmac.xci"]"\
 "[file normalize "$origin_dir/src/ip/ila_cmac/ila_cmac.xci"]"\
 "[file normalize "$origin_dir/src/rtl/define/TDI_define.vh"]"\
 "[file normalize "$origin_dir/src/ip/ernic_0/ernic_0.xci"]"\
 "[file normalize "$origin_dir/src/ip/vio_reg_config/vio_reg_config.xci"]"\
 "[file normalize "$origin_dir/src/ip/ddr4_test/ddr4_test.xci"]"\
 "[file normalize "$origin_dir/src/ip/TDI_fifo/TDI_fifo.xci"]"\
 "[file normalize "$origin_dir/src/ip/clk_wiz_0/clk_wiz_0.xci"]"\
 "[file normalize "$origin_dir/src/ip/qp_blk_mem/qp_blk_mem.xci"]"\
 "[file normalize "$origin_dir/src/ip/qp_axi_bram_ctrl/qp_axi_bram_ctrl.xci"]"\
 "[file normalize "$origin_dir/src/ip/vio_rst/vio_rst.xci"]"\
 "[file normalize "$origin_dir/src/ip/vio_TDI_sim_param/vio_TDI_sim_param.xci"]"\
 "[file normalize "$origin_dir/src/ip/cmac_usplus/cmac_usplus.xci"]"\
 "[file normalize "$origin_dir/src/ip/axi_interconnect_0/axi_interconnect_0.xci"]"\
 "[file normalize "$origin_dir/src/xdc/config.xdc"]"\
 "[file normalize "$origin_dir/src/xdc/debug.xdc"]"\
 "[file normalize "$origin_dir/src/xdc/pin.xdc"]"\
 "[file normalize "$origin_dir/src/xdc/timing.xdc"]"\
 "[file normalize "$origin_dir/src/xdc/ddr4_c1_pin.xdc"]"\
 "[file normalize "$origin_dir/src/xdc/ddr4_c0_pin.xdc"]"\
 "[file normalize "$origin_dir/src/tb/Host_pkt_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/Host_sim.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/arch_defines.v"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/arch_package.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/MemoryArray.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_sdram_model_wrapper.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/proj_package.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/StateTableCore.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/StateTable.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_model.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_model_tb_top.sv"]"\
 "[file normalize "$origin_dir/src/tb/decompression.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/interface.sv"]"\
 "[file normalize "$origin_dir/src/tb/top_tb.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/bd_8530_lmb_bram_I_0.mem"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/bd_8530_second_lmb_bram_I_0.mem"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_axi_wrapper.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_custom_mode_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_prbs_mode_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/microblaze_mcs_0.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_boot_mode_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_axi_opcode_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_data_gen.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_axi_tg_top.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/ddr4_v2_2_data_chk.sv"]"\
 "[file normalize "$origin_dir/src/tb/ddr_sim/glbl.v"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set paths [list \
   [file normalize "$origin_dir/../ip_repo/ernic_3_1"] \
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "DataProcBoard"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "DataProcBoard_proj.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu3p-ffvc1517-2-i

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "49" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "49" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "49" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "49" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "49" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "49" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "49" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "343" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/../ip_repo/ernic_3_1"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/rtl/TMP75.v" ]\
 [file normalize "${origin_dir}/src/rtl/CMAC/cmac_usplus_config.v" ]\
 [file normalize "${origin_dir}/src/rtl/CMAC/cmac_usplus_rx_config.v" ]\
 [file normalize "${origin_dir}/src/rtl/CMAC/cmac_usplus_tx_config.v" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_8b.v" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/ernic_0_rnic_exdes_crc32_zero_extnd.v" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/ernic_0_rnic_exdes_crc_wrap.v" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/ernic_0_rnic_exdes_icrc_calc.v" ]\
 [file normalize "${origin_dir}/src/rtl/CMAC/CMAC_monitor.sv" ]\
 [file normalize "${origin_dir}/src/rtl/DDR_PROC/DDR4_proc.sv" ]\
 [file normalize "${origin_dir}/src/rtl/define/XRNIC_define.vh" ]\
 [file normalize "${origin_dir}/src/rtl/define/Board_define.vh" ]\
 [file normalize "${origin_dir}/src/rtl/define/ETH_pkt_define.sv" ]\
 [file normalize "${origin_dir}/src/rtl/define/XRNIC_REG_configuration.vh" ]\
 [file normalize "${origin_dir}/src/rtl/DDR_PROC/DDR4_write_proc.sv" ]\
 [file normalize "${origin_dir}/src/rtl/define/proj_define.vh" ]\
 [file normalize "${origin_dir}/src/rtl/Data_proc_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/FAN_ctr_module.sv" ]\
 [file normalize "${origin_dir}/src/rtl/INFO_PROC/INFO_data_sim.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/QPn_LUT.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/RDMA_fsm.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA_proc_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/RoCE_CM_rx_proc.sv" ]\
 [file normalize "${origin_dir}/src/rtl/TDI_PROC/TDI_data_proc.sv" ]\
 [file normalize "${origin_dir}/src/rtl/TDI_PROC/TDI_data_proc_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/TDI_PROC/TDI_data_sim.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/XRNIC_WQE_manager_new.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/XRNIC_reg_config_fsm.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/XRNIC_rx_path_proc.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/XRNIC_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/arp_rx.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/arp_table.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/arp_tx.sv" ]\
 [file normalize "${origin_dir}/src/rtl/axi_bram.sv" ]\
 [file normalize "${origin_dir}/src/rtl/RDMA/axi_lite_interface.sv" ]\
 [file normalize "${origin_dir}/src/rtl/CMAC/cmac_usplus_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/eth_pkt_proc_top.sv" ]\
 [file normalize "${origin_dir}/src/rtl/rst_gen.sv" ]\
 [file normalize "${origin_dir}/src/rtl/rst_usr_gen.sv" ]\
 [file normalize "${origin_dir}/src/rtl/ETH_PKT_PROC/rx_pkt_decode.sv" ]\
 [file normalize "${origin_dir}/src/rtl/top.sv" ]\
 [file normalize "${origin_dir}/src/ip/vio_cmac/vio_cmac.xci" ]\
 [file normalize "${origin_dir}/src/ip/ila_cmac/ila_cmac.xci" ]\
 [file normalize "${origin_dir}/src/rtl/define/TDI_define.vh" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "CMAC/CMAC_monitor.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "DDR_PROC/DDR4_proc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "define/XRNIC_define.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "define/Board_define.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "define/ETH_pkt_define.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "define/XRNIC_REG_configuration.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "DDR_PROC/DDR4_write_proc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "define/proj_define.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "rtl/Data_proc_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/FAN_ctr_module.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "INFO_PROC/INFO_data_sim.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/QPn_LUT.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/RDMA_fsm.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/RDMA_proc_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/RoCE_CM_rx_proc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "TDI_PROC/TDI_data_proc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "TDI_PROC/TDI_data_proc_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "TDI_PROC/TDI_data_sim.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/XRNIC_WQE_manager_new.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/XRNIC_reg_config_fsm.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/XRNIC_rx_path_proc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/XRNIC_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/arp_rx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/arp_table.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/arp_tx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/axi_bram.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "RDMA/axi_lite_interface.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CMAC/cmac_usplus_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/eth_pkt_proc_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/rst_gen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/rst_usr_gen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ETH_PKT_PROC/rx_pkt_decode.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "vio_cmac/vio_cmac.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "ila_cmac/ila_cmac.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "define/TDI_define.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/ernic_0/ernic_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ernic_0/ernic_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/vio_reg_config/vio_reg_config.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "vio_reg_config/vio_reg_config.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/ddr4_test/ddr4_test.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ddr4_test/ddr4_test.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/TDI_fifo/TDI_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "TDI_fifo/TDI_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/clk_wiz_0/clk_wiz_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_0/clk_wiz_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/qp_blk_mem/qp_blk_mem.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "qp_blk_mem/qp_blk_mem.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/qp_axi_bram_ctrl/qp_axi_bram_ctrl.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "qp_axi_bram_ctrl/qp_axi_bram_ctrl.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/vio_rst/vio_rst.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "vio_rst/vio_rst.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/vio_TDI_sim_param/vio_TDI_sim_param.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "vio_TDI_sim_param/vio_TDI_sim_param.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/cmac_usplus/cmac_usplus.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "cmac_usplus/cmac_usplus.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/ip/axi_interconnect_0/axi_interconnect_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "axi_interconnect_0/axi_interconnect_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/config.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/config.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/debug.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/debug.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "used_in" -value "implementation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/pin.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/pin.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/timing.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/timing.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/ddr4_c1_pin.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/ddr4_c1_pin.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/xdc/ddr4_c0_pin.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/ddr4_c0_pin.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files *xdc/debug.xdc]" -objects $obj
set_property -name "target_part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "target_ucf" -value "[get_files *xdc/debug.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/tb/Host_pkt_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/Host_sim.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/arch_defines.v" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/arch_package.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/MemoryArray.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_sdram_model_wrapper.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/proj_package.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/StateTableCore.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/StateTable.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_model.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_model_tb_top.sv" ]\
 [file normalize "${origin_dir}/src/tb/decompression.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/interface.sv" ]\
 [file normalize "${origin_dir}/src/tb/top_tb.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/bd_8530_lmb_bram_I_0.mem" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/bd_8530_second_lmb_bram_I_0.mem" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_axi_wrapper.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_custom_mode_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_prbs_mode_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/microblaze_mcs_0.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_boot_mode_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_axi_opcode_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_data_gen.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_axi_tg_top.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/ddr4_v2_2_data_chk.sv" ]\
 [file normalize "${origin_dir}/src/tb/ddr_sim/glbl.v" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "tb/Host_pkt_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "tb/Host_sim.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/arch_package.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/MemoryArray.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_sdram_model_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/proj_package.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/StateTableCore.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/StateTable.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_model.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "tb/ddr_model_tb_top.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "tb/decompression.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/interface.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "tb/top_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/bd_8530_lmb_bram_I_0.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "ddr_sim/bd_8530_second_lmb_bram_I_0.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_axi_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_custom_mode_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_prbs_mode_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/microblaze_mcs_0.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_boot_mode_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_axi_opcode_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_data_gen.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_axi_tg_top.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "ddr_sim/ddr4_v2_2_data_chk.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "top_tb" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.add_positional" -value "1" -objects $obj
set_property -name "xsim.simulate.log_all_signals" -value "1" -objects $obj
set_property -name "xsim.simulate.no_quit" -value "1" -objects $obj
set_property -name "xsim.simulate.saif_all_signals" -value "1" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu3p-ffvc1517-2-i -flow {Vivado Synthesis 2021} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2021" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "D:/project/DataProcBoard_git/DataProcBoard.srcs/utils_1/imports/synth_1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'synth_2' run (if not found)
if {[string equal [get_runs -quiet synth_2] ""]} {
    create_run -name synth_2 -part xcvu3p-ffvc1517-2-i -flow {Vivado Synthesis 2021} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_2]
  set_property flow "Vivado Synthesis 2021" [get_runs synth_2]
}
set obj [get_runs synth_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_2_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_2_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_2
}
set obj [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_2]
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'synth_3' run (if not found)
if {[string equal [get_runs -quiet synth_3] ""]} {
    create_run -name synth_3 -part xcvu3p-ffvc1517-2-i -flow {Vivado Synthesis 2021} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_3]
  set_property flow "Vivado Synthesis 2021" [get_runs synth_3]
}
set obj [get_runs synth_3]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_3_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_3] synth_3_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_3_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_3
}
set obj [get_report_configs -of_objects [get_runs synth_3] synth_3_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_3]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_2]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu3p-ffvc1517-2-i -flow {Vivado Implementation 2021} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2021" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "D:/project/DataProcBoard_git/DataProcBoard.srcs/utils_1/imports/impl_1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'impl_2' run (if not found)
if {[string equal [get_runs -quiet impl_2] ""]} {
    create_run -name impl_2 -part xcvu3p-ffvc1517-2-i -flow {Vivado Implementation 2021} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_2
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_2]
  set_property flow "Vivado Implementation 2021" [get_runs impl_2]
}
set obj [get_runs impl_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_2_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0] "" ] } {
  create_report_config -report_name impl_2_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_2_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_2_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_2_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0] "" ] } {
  create_report_config -report_name impl_2_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_2_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_2_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_2_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_2_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_2_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_2]
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'impl_3' run (if not found)
if {[string equal [get_runs -quiet impl_3] ""]} {
    create_run -name impl_3 -part xcvu3p-ffvc1517-2-i -flow {Vivado Implementation 2021} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_3
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_3]
  set_property flow "Vivado Implementation 2021" [get_runs impl_3]
}
set obj [get_runs impl_3]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_3_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_3_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_3_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_io_0] "" ] } {
  create_report_config -report_name impl_3_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_3_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_3_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_3_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_3_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_3_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_3_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_3_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_3_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_3_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_3_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_3_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_power_0] "" ] } {
  create_report_config -report_name impl_3_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_3_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_3_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_3_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_3_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_3_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_3_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_3_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_3_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_3_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_3] impl_3_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_3_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_3
}
set obj [get_report_configs -of_objects [get_runs impl_3] impl_3_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_3]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcvu3p-ffvc1517-2-i" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_2]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
