set_property -dict {PACKAGE_PIN D24  IOSTANDARD DIFF_SSTL15} [get_ports ddr_clk_p]
set_property -dict {PACKAGE_PIN C24  IOSTANDARD DIFF_SSTL15} [get_ports ddr_clk_n]


set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_pins -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcme*.u_mmcme_adv_inst/CLKIN1}]


set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_dq[*]   ]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[0]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[0]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[1]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[1]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[2]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[2]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[3]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[3]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[4]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[4]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[5]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[5]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[6]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[6]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_n[7]]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_dqs_p[7]]


set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_addr[*] ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_ba[*]   ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_ras_n   ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_cas_n   ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_we_n    ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_reset_n ]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_ck_p    ]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports  ddr3_ck_n    ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_cke     ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_cs_n    ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_dm[*]   ]
set_property IOSTANDARD SSTL15_DCI [get_ports  ddr3_odt     ]

set_property PACKAGE_PIN   E28    [get_ports {ddr3_addr[0]  }]
set_property PACKAGE_PIN   E27    [get_ports {ddr3_addr[1]  }]
set_property PACKAGE_PIN   D28    [get_ports {ddr3_addr[10]  }]
set_property PACKAGE_PIN   B29    [get_ports {ddr3_addr[11]  }]
set_property PACKAGE_PIN   B27    [get_ports {ddr3_addr[12]  }]
set_property PACKAGE_PIN   C28    [get_ports {ddr3_addr[13]  }]
set_property PACKAGE_PIN   D26    [get_ports {ddr3_addr[14]  }]
set_property PACKAGE_PIN   B25    [get_ports {ddr3_addr[15]  }]
set_property PACKAGE_PIN   E26    [get_ports {ddr3_addr[2]  }]
set_property PACKAGE_PIN   D29    [get_ports {ddr3_addr[3]  }]
set_property PACKAGE_PIN   A29    [get_ports {ddr3_addr[4]  }]
set_property PACKAGE_PIN   C27    [get_ports {ddr3_addr[5]  }]
set_property PACKAGE_PIN   A28    [get_ports {ddr3_addr[6]  }]
set_property PACKAGE_PIN   A27    [get_ports {ddr3_addr[7]  }]
set_property PACKAGE_PIN   G22    [get_ports {ddr3_addr[8]  }]
set_property PACKAGE_PIN   F27    [get_ports {ddr3_addr[9]  }]
set_property PACKAGE_PIN   A25    [get_ports {ddr3_ba[0]     }]
set_property PACKAGE_PIN   C26    [get_ports {ddr3_ba[1]     }]
set_property PACKAGE_PIN   B26    [get_ports {ddr3_ba[2]     }]

set_property PACKAGE_PIN   F23    [get_ports {ddr3_cas_n     }]
set_property PACKAGE_PIN   A24    [get_ports {ddr3_ck_n      }]
set_property PACKAGE_PIN   B24    [get_ports {ddr3_ck_p      }]
set_property PACKAGE_PIN   F25    [get_ports {ddr3_cke       }]
set_property PACKAGE_PIN   F24    [get_ports {ddr3_cs_n      }]

set_property PACKAGE_PIN   B14    [get_ports {ddr3_dm[0]     }]
set_property PACKAGE_PIN   D14    [get_ports {ddr3_dm[1]     }]
set_property PACKAGE_PIN   G17    [get_ports {ddr3_dm[2]     }]
set_property PACKAGE_PIN   J15    [get_ports {ddr3_dm[3]     }]
set_property PACKAGE_PIN   F8     [get_ports {ddr3_dm[4]     }]
set_property PACKAGE_PIN   L8     [get_ports {ddr3_dm[5]     }]
set_property PACKAGE_PIN   H11    [get_ports {ddr3_dm[6]     }]
set_property PACKAGE_PIN   E11    [get_ports {ddr3_dm[7]     }]

set_property PACKAGE_PIN   A19    [get_ports {ddr3_dq[0]     }]
set_property PACKAGE_PIN   B17    [get_ports {ddr3_dq[1]     }]
set_property PACKAGE_PIN   D16    [get_ports {ddr3_dq[10]    }]
set_property PACKAGE_PIN   F14    [get_ports {ddr3_dq[11]    }]
set_property PACKAGE_PIN   E16    [get_ports {ddr3_dq[12]    }]
set_property PACKAGE_PIN   F15    [get_ports {ddr3_dq[13]    }]
set_property PACKAGE_PIN   E15    [get_ports {ddr3_dq[14]    }]
set_property PACKAGE_PIN   E18    [get_ports {ddr3_dq[15]    }]
set_property PACKAGE_PIN   F18    [get_ports {ddr3_dq[16]    }]
set_property PACKAGE_PIN   G15    [get_ports {ddr3_dq[17]    }]
set_property PACKAGE_PIN   H17    [get_ports {ddr3_dq[18]    }]
set_property PACKAGE_PIN   F17    [get_ports {ddr3_dq[19]    }]
set_property PACKAGE_PIN   A18    [get_ports {ddr3_dq[2]     }]
set_property PACKAGE_PIN   H18    [get_ports {ddr3_dq[20]    }]
set_property PACKAGE_PIN   G14    [get_ports {ddr3_dq[21]    }]
set_property PACKAGE_PIN   H16    [get_ports {ddr3_dq[22]    }]
set_property PACKAGE_PIN   H19    [get_ports {ddr3_dq[23]    }]
set_property PACKAGE_PIN   J16    [get_ports {ddr3_dq[24]    }]
set_property PACKAGE_PIN   L15    [get_ports {ddr3_dq[25]    }]
set_property PACKAGE_PIN   K15    [get_ports {ddr3_dq[26]    }]
set_property PACKAGE_PIN   L19    [get_ports {ddr3_dq[27]    }]
set_property PACKAGE_PIN   K18    [get_ports {ddr3_dq[28]    }]
set_property PACKAGE_PIN   L18    [get_ports {ddr3_dq[29]    }]
set_property PACKAGE_PIN   B16    [get_ports {ddr3_dq[3]     }]
set_property PACKAGE_PIN   K17    [get_ports {ddr3_dq[30]    }]
set_property PACKAGE_PIN   K16    [get_ports {ddr3_dq[31]    }]
set_property PACKAGE_PIN   D9     [get_ports {ddr3_dq[32]    }]
set_property PACKAGE_PIN   B9     [get_ports {ddr3_dq[33]    }]
set_property PACKAGE_PIN   D10    [get_ports {ddr3_dq[34]    }]
set_property PACKAGE_PIN   C9     [get_ports {ddr3_dq[35]    }]
set_property PACKAGE_PIN   E10    [get_ports {ddr3_dq[36]    }]
set_property PACKAGE_PIN   C8     [get_ports {ddr3_dq[37]    }]
set_property PACKAGE_PIN   D8     [get_ports {ddr3_dq[38]    }]
set_property PACKAGE_PIN   A9     [get_ports {ddr3_dq[39]    }]
set_property PACKAGE_PIN   C17    [get_ports {ddr3_dq[4]     }]
set_property PACKAGE_PIN   H8     [get_ports {ddr3_dq[40]    }]
set_property PACKAGE_PIN   G9     [get_ports {ddr3_dq[41]    }]
set_property PACKAGE_PIN   J9     [get_ports {ddr3_dq[42]    }]
set_property PACKAGE_PIN   F10    [get_ports {ddr3_dq[43]    }]
set_property PACKAGE_PIN   J8     [get_ports {ddr3_dq[44]    }]
set_property PACKAGE_PIN   F9     [get_ports {ddr3_dq[45]    }]
set_property PACKAGE_PIN   G10    [get_ports {ddr3_dq[46]    }]
set_property PACKAGE_PIN   H9     [get_ports {ddr3_dq[47]    }]
set_property PACKAGE_PIN   H13    [get_ports {ddr3_dq[48]    }]
set_property PACKAGE_PIN   G12    [get_ports {ddr3_dq[49]    }]
set_property PACKAGE_PIN   B15    [get_ports {ddr3_dq[5]     }]
set_property PACKAGE_PIN   J13    [get_ports {ddr3_dq[50]    }]
set_property PACKAGE_PIN   J11    [get_ports {ddr3_dq[51]    }]
set_property PACKAGE_PIN   K11    [get_ports {ddr3_dq[52]    }]
set_property PACKAGE_PIN   K12    [get_ports {ddr3_dq[53]    }]
set_property PACKAGE_PIN   L12    [get_ports {ddr3_dq[54]    }]
set_property PACKAGE_PIN   H12    [get_ports {ddr3_dq[55]    }]
set_property PACKAGE_PIN   B12    [get_ports {ddr3_dq[56]    }]
set_property PACKAGE_PIN   A13    [get_ports {ddr3_dq[57]    }]
set_property PACKAGE_PIN   A12    [get_ports {ddr3_dq[58]    }]
set_property PACKAGE_PIN   D13    [get_ports {ddr3_dq[59]    }]
set_property PACKAGE_PIN   C18    [get_ports {ddr3_dq[6]     }]
set_property PACKAGE_PIN   B11    [get_ports {ddr3_dq[60]    }]
set_property PACKAGE_PIN   C13    [get_ports {ddr3_dq[61]    }]
set_property PACKAGE_PIN   C11    [get_ports {ddr3_dq[62]    }]
set_property PACKAGE_PIN   C12    [get_ports {ddr3_dq[63]    }]
set_property PACKAGE_PIN   A15    [get_ports {ddr3_dq[7]     }]
set_property PACKAGE_PIN   D15    [get_ports {ddr3_dq[8]     }]
set_property PACKAGE_PIN   E17    [get_ports {ddr3_dq[9]     }]

set_property PACKAGE_PIN   B19    [get_ports {ddr3_dqs_n[0]  }]
set_property PACKAGE_PIN   D18    [get_ports {ddr3_dqs_n[1]  }]
set_property PACKAGE_PIN   F19    [get_ports {ddr3_dqs_n[2]  }]
set_property PACKAGE_PIN   J18    [get_ports {ddr3_dqs_n[3]  }]
set_property PACKAGE_PIN   A10    [get_ports {ddr3_dqs_n[4]  }]
set_property PACKAGE_PIN   J10    [get_ports {ddr3_dqs_n[5]  }]
set_property PACKAGE_PIN   K13    [get_ports {ddr3_dqs_n[6]  }]
set_property PACKAGE_PIN   E13    [get_ports {ddr3_dqs_n[7]  }]
set_property PACKAGE_PIN   C19    [get_ports {ddr3_dqs_p[0]  }]
set_property PACKAGE_PIN   D19    [get_ports {ddr3_dqs_p[1]  }]
set_property PACKAGE_PIN   G19    [get_ports {ddr3_dqs_p[2]  }]
set_property PACKAGE_PIN   J19    [get_ports {ddr3_dqs_p[3]  }]
set_property PACKAGE_PIN   B10    [get_ports {ddr3_dqs_p[4]  }]
set_property PACKAGE_PIN   K10    [get_ports {ddr3_dqs_p[5]  }]
set_property PACKAGE_PIN   L13    [get_ports {ddr3_dqs_p[6]  }]
set_property PACKAGE_PIN   F13    [get_ports {ddr3_dqs_p[7]  }]

set_property PACKAGE_PIN   G20    [get_ports {ddr3_odt       }]
set_property PACKAGE_PIN   E21    [get_ports {ddr3_ras_n     }]
set_property PACKAGE_PIN   F20    [get_ports {ddr3_reset_n   }]
set_property PACKAGE_PIN   E20    [get_ports {ddr3_we_n      }]




